[tool.poetry]
name = "blog-site"
version = "0.1.0"
description = ""
authors = ["Julia Chuprova <nikaniks57@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
