# Generated by Django 4.2.6 on 2023-12-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
